//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace consumo.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONSUMO
    {
        public int id { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string cod_bodega { get; set; }
        public string cod_articulo { get; set; }
        public string can_cerdo { get; set; }
        public string nota { get; set; }
        public Nullable<decimal> consuXcerdo { get; set; }
        public Nullable<decimal> sobro { get; set; }
        public Nullable<decimal> entrada { get; set; }
        public Nullable<decimal> consumo1 { get; set; }
        public Nullable<decimal> sobro_anterior { get; set; }
    }
}
