//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace consumo.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entradas
    {
        public string Codigo_Granja { get; set; }
        public string Codigo_Galeron { get; set; }
        public string Codigo_Corral { get; set; }
        public string Lote_Actual { get; set; }
        public System.DateTime F_Movimiento { get; set; }
        public string Codigo_Evento { get; set; }
        public decimal Cantidad { get; set; }
        public string Numero_Movimiento { get; set; }
    
        public virtual Corrales Corrales { get; set; }
        public virtual Eventos Eventos { get; set; }
        public virtual Lote2 Lote2 { get; set; }
        public virtual Mov_Evento Mov_Evento { get; set; }
    }
}
