//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace consumo.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lote1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lote1()
        {
            this.Lote2 = new HashSet<Lote2>();
        }
    
        public string Codigo_Lote { get; set; }
        public System.DateTime F_Nacimiento { get; set; }
        public System.DateTime F_Destete { get; set; }
        public decimal Peso_Destete { get; set; }
        public Nullable<decimal> Peso_Nacimiento { get; set; }
        public string Usuario_Crea { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lote2> Lote2 { get; set; }
    }
}
