//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace consumo.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mov_Evento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mov_Evento()
        {
            this.Entradas = new HashSet<Entradas>();
        }
    
        public string Codigo_Evento { get; set; }
        public string Numero_Movimiento { get; set; }
        public System.DateTime Fecha_Movimiento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entradas> Entradas { get; set; }
        public virtual Eventos Eventos { get; set; }
    }
}
