//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace consumo.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salida_Muerte
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Salida_Muerte()
        {
            this.Salidas = new HashSet<Salidas>();
        }
    
        public string Codigo_Evento { get; set; }
        public string Lote_Actual { get; set; }
        public string Codigo_Causa { get; set; }
        public string F_Salida { get; set; }
        public decimal Peso_Pie { get; set; }
        public string Boleta { get; set; }
        public decimal Cantidad { get; set; }
    
        public virtual Causas_Muertes Causas_Muertes { get; set; }
        public virtual Eventos Eventos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Salidas> Salidas { get; set; }
    }
}
