//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace consumo.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salidas_Matadero
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Salidas_Matadero()
        {
            this.Salidas = new HashSet<Salidas>();
        }
    
        public string Codigo_Evento { get; set; }
        public string Lote_Actual { get; set; }
        public System.DateTime F_Nacimiento { get; set; }
        public Nullable<System.DateTime> F_Matanza { get; set; }
        public Nullable<System.DateTime> F_Salida { get; set; }
        public decimal Peso_Pie { get; set; }
        public decimal Peso_Canal { get; set; }
        public string Boleta { get; set; }
        public string Grasa_16a19 { get; set; }
        public string Grasa_Mas19 { get; set; }
        public string Codigo_Venta { get; set; }
        public decimal Cantidad { get; set; }
        public string Edad { get; set; }
        public string Grasa { get; set; }
        public string Magra { get; set; }
    
        public virtual Eventos Eventos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Salidas> Salidas { get; set; }
        public virtual Ventas Ventas { get; set; }
    }
}
